TRAIN:
  WARMUP_LR: 5e-6
  BASE_LR: 5e-3
  MIN_LR: 5e-5
DATA:
  IMG_SIZE: 32
MODEL:
  TYPE: swin
  NAME: swin_32x32
  DROP_PATH_RATE: 0.2
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [2, 4, 8]
    NUM_HEADS: [ 3, 6, 12]
    WINDOW_SIZE: 4